World114 update
mapcrafter/mapcrafter pull request #327
Opened 2019-04-21 15:32 UTC by miclav

This pull request contains spritemap updated for the 1.14 update, and includes the quick patch from Moritz Neikes  (https://github.com/mapcrafter/mapcrafter/issues/317#issuecomment-468392202)  for chunk loading 1.14.
Some blocks needed special code for the update to work.
- Composter
- Bamboo
- Signs
The only blocks not fully implemented yet is the bell, it's only displaying the bell support.
![image](https://user-images.githubusercontent.com/11891522/56472155-04e40580-6429-11e9-957a-aca8fc23d1f4.png)

2019-04-24 08:07 UTC, m0r13 requested changes
Just two little things.

2019-04-24 08:07 UTC, m0r13 commented on src/mapcraftercore/mc/chunk.cpp
> +               if (!(tag.payload == "fullchunk" || tag.payload == "full" || tag.payload == "postprocessed" || tag.payload == "mobs_spawned")) {
Please indent this with tabs.

2019-04-24 08:07 UTC, m0r13 commented on src/mapcraftercore/mc/chunk.cpp
> +               if(section_tag.hasArray<nbt::TagByteArray>("BlockLight", 2048))
Please use tabs for indentation here as well. And look how I placed the curly brackets in the remaining code, also note the space between `if` and the condition.

2019-04-24 08:07 UTC, m0r13 commented on src/mapcraftercore/renderer/blocktextures.cpp
> +	: ACACIA_DOOR_BOTTOM("acacia_door_bottom"),
Just FYI, this doesn't need to be updated as Mapcrafter doesn't need the Minecraft texture files anymore (but only the generated block images instead). We can keep it as it is now though.

2019-04-24 08:09 UTC, m0r13 commented
Hey. Thanks for helping out and making the PR! I looked at the code... Just two little things then I would merge it and see that I build some binaries for that version again.

2019-04-25 14:12 UTC, miclav commented
Hi
Sure thing, I'll work on those tonight. Sorry about the tab indent, I should have known better :(
I will send as well a PR for blockcrafter, the changes to add missing blockstates.

2019-04-26 02:07 UTC, miclav commented
Changes made

2019-04-30 21:21 UTC, beulette commented
I had to add set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11") in CMakeList.txt

Or I had an issue when launching "make":
"#error This file requires compiler and library support for the ISO C++ 2011 standard".

And then I compiled til 62% with this error (at Building CXX object mapcraftercore/CMakeFiles/mapcraftercore.dir/util/logging.o):
```
###/src/mapcraftercore/util/logging.cpp: In member function ‘virtual void mapcrafter::util::LogSyslogSink::sink(const mapcrafter::util::LogMessage&)’:
###/src/mapcraftercore/util/logging.cpp:269:56: warning: format not a string literal and no format arguments [-Wformat-security]
    util::replaceAll(message.message, "%", "%%").c_str());
```

And then at 71% ([ 71%] Linking CXX executable mapcrafter) I had a lot of "undefined references" just like sarbot.

I just found here that someone says "There were changes to the <string> class in the C++11 standard which may conflict with versions of the Boost library that were compiled with a non-C++11 compiler (such as G++-4.8). Try recompiling boost or using a version of C++ compiler that was used to compile your Boost libraries." (source: https://stackoverflow.com/questions/12179154/undefined-reference-to-boostprogram-optionsoptions-descriptionm-default-l)

2019-05-01 20:29 UTC, miclav commented
Hey @sarbot 
To answer your question, I didn't change anything in the project but few lines of code and resource files. The build process for world113 should be identical to world114.
And thanks @beulette for troubleshooting and clarifying the compiling issue.

2019-05-01 23:24 UTC, orion78fr commented
Using `cmake . && make` on this branch worked perfectly for my 1.14 map on Arch Linux. I had residual files from the 1.13 branch, so it may be that.

2019-05-07 15:57 UTC, 25A0 commented
Hi @miclav, I just want to thank you for turning my patch into a proper PR, and for the other work you've done here! 🎉

2019-05-07 18:18 UTC, m0r13 approved these changes

2019-05-07 18:19 UTC, m0r13 commented
Looks good now! I'll merge it and see that I'll trigger some builds too.

2019-05-07 18:20 UTC, merged